### ISSUE TITLE
Install All The Tropes Wiki extensions

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#126]
@Arcane21 feel free to comment. These are likely not all the extensions you've requested, I just picked some randomly.
- [x] AdminLinks
- [x] CSS (I wonder if this doesn't introduce XSS vulnerabilities, because it's possible to execute JavaScript from CSS)
- [x] DPLForum (This one will be converted to Flow too)
- [x] ImageMap
- [x] LiquidThreads (Do you really want this instead of Flow? We can covert existing topics to Flow topics)
- [x] NewUserMessage
- [x] PageImages
- [x] Poem
- [x] Popups
- [x] Math
- [x] SyntaxHighlight_GeSHi
- [x] Tabber (I'd like to replace this one with the Tabs extension, because it's in Wikimedia version control)
- [x] TemplateSandbox
- [x] TextExtracts
- [x] Variables
- [x] VectorBeta
- [x] Monaco (https://github.com/Arcane21/monaco-port)
- [ ] NativeSvgHandler 
- [x] Foreground 
- [ ] https://www.mediawiki.org/wiki/Extension:PageNotice
- [ ] https://www.mediawiki.org/wiki/Extension:SandboxLink
- [ ] WikiLove

**Comment by Arcane21** [comment]
You can ditch SimpleMathJax (Math is preferred), and yes, please convert all existing LiquidThreads topics to Flow.

**Comment by Southparkfan** [comment]
Can I replace Tabber with Tabs too? I don't disallow usage of Tabber, but extensions that I can find on git.wikimedia.org have various benefits (e.g. continious i18n updates, 'free removal' of deprecated stuff), and for me that's a +1.

**Comment by Arcane21** [comment]
We use both in different areas, and Tabber is pretty stable (Wikia still makes regular use of it and I checked, works just fine with MW 1.25)

**Comment by Arcane21** [comment]
CSS is secure. I've tested it, and it has no reported XSS holes. It's also needed for a lot of our subpages.

Also, link for all the features we need ASAP:

https://voat.co/v/allthetropes/comments/49716

**Comment by Arcane21** [comment]
We will need the followign extensions, bare minimum, plus all the images, just to get us up and going. The rest can be done later.

* Babel (need for userboxes)	
* CharInsert (template inserts in Edittools require this)	
* CSS (for Darth/Sugar Wiki code to work right)	
* EmbedVideo	
* ImageMap	
* NoTitle (used on title page}
* RandomSelection (need for Featured Articles to work properly)
* RelatedArticles (some pages make use of the functions of this extension)
* Subpage List 3	
* Vote (used for our review pages)	
* NativeSvgHandler	
* Highlight Link in Category
* MultiBoilerplate (for page creation template functionality)		
* NewUserMessage (used for auto welcoming new users)

**Comment by NDKilla** [comment]
Math and Poem are enabled globally, checked as done in OP.
Image map done and enabled on ATT.

**Comment by Arcane21** [comment]
On top of needing several more extensions, our image import does not seem to have taken properly, as many images are reported present but are not, and they should be included with the initial dump provided to Miraheze.

Further, VisualEditor does not seem to load properly.

**Comment by revi** [comment]
Images: make a new issue.
VE: Leave it to others.

**Comment by NDKilla** [comment]
Checked off some extensions per [e83659](https://github.com/miraheze/mediawiki/commit/e836593b2da1e3756bbb2b6ba9e930d60d6b9fa0)

**Comment by NDKilla** [comment]
Downloaded syntaxhighlight_geshi but currently not enabled per #161 and my likely stupidity. 
after i get this down I'll try to finish some of these up for you guys.

**Comment by NDKilla** [comment]
Worth noting that syntax highlight was enabled and then disabled. Looking into it. 

Also planning on handling more of these later since I've been getting such little sleep lately

**Comment by Southparkfan** [comment]
RelatedArticles and MultiBoilerplate done.

**Comment by Arcane21** [comment]
Please add the following settings for MultiBoilerplate

$wgMultiBoilerplateDisplaySpecialPage = true;
$wgMultiBoilerplateOptions = false;

(Tested these settingzs with latest version of MB extension, confirm they work)

Also, the following extensions/skins still need to be enabled:

* PageTriage
* Monaco (may want to be globally enabled, Miraheze has my guarantee I actively maintain it)	
** This version (https://github.com/Arcane21/monaco-port)
* SectionHide (may need to acquire here)
** https://github.com/Orain/SectionHide
* Subpage List 3
* NativeSvgHandler	(recommend Miraheze install this globally, it's a nice fallback in case normal SVG rendering fails, as it defaults to the user's browser internal SVG rendering, resulting in no client side issues, will not affect anything otherwise)
* Foreground (Foreground skin, may want to make this globally available)

**Comment by Reception123** [comment]
TemplateSandbox installed.

**Comment by Arcane21** [comment]
Still require the following:

VectorBeta needs installed (please set all possible features to True) and it and Popups need to be opt-in features of BetaFeatures.

Also, the following extensions/skins still need to be enabled:

* Monaco (may want to be globally enabled, Miraheze has my guarantee I actively maintain it)	
** This version (https://github.com/Arcane21/monaco-port)
* NativeSvgHandler	(recommend Miraheze install this globally, it's a nice fallback in case normal SVG rendering fails, as it defaults to the user's browser internal SVG rendering, resulting in no client side issues, will not affect anything otherwise)
* Foreground (Foreground skin, may want to make this globally available)
* https://www.mediawiki.org/wiki/Extension:PageNotice

**Comment by Arcane21** [comment]
Really hate to be a nag, but are the remaining extensions going to ever be added. We could also use our Vote extension to fix our reviews pages and Inputbox if it has no further problems.

**Comment by Reception123** [comment]
Well the only remaining one on the list is VectorBeta, which was added but I don't think it was actually enabled.

**Comment by Reception123** [comment]
From the list there are none left (Vector Beta is enabled but no one checked it off the list).

**Comment by Arcane21** [comment]
Everything we need aside from what I mentioned is listed here;

https://github.com/miraheze/mw-config/issues/126#issuecomment-154767214

**Comment by Reception123** [comment]
@Arcane21 Ok. Foreground is on the point of being installed, only SPF can do it (as he needs to agree to it). I will remind him. The rest I will try to do ASAP.

**Comment by NDKilla** [comment]
Updated the original post to include several extensions mentioned by @Arcane21 that I don't believe are installed yet. I'm about to get some ZZZZs, sorry for the delay @Arcane21 and others

**Comment by Reception123** [comment]
Foreground is installed, but some configuration needs to be done by SPF.

**Comment by Southparkfan** [comment]
@Arcane21 Foreground is installed.

**Comment by Reception123** [comment]
Monaco skin on the point of being installed.

**Comment by Reception123** [comment]
Monaco is being installed/configured.

**Comment by Reception123** [comment]
@Arcane21 Monaco was done a few days ago

**Comment by Arcane21** [comment]
We still need the following installed if they are not already in the pipeline;

BetaFeatures
NativeSvgHandler
https://www.mediawiki.org/wiki/Extension:PageNotice
https://www.mediawiki.org/wiki/Extension:SandboxLink
WikiLove
Vote

**Comment by JohnFLewis** [comment]
I feel this issue is grossly mis-checked and used as 6 months is far far too long for something to be resolved when other requests are being done quicker.

As such, @arcane21 could you (or any other eagle eyes viewer create s separate issue for all extensions needing to be installed?

SandboxLink also to my knowledge can be done via a gadget (which will be more useful).

We also need to get out if the culture of long list issue as this proves - they never work effectively.
