### ISSUE TITLE
GeSHi causes HHVM SegFault

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#169]
root@mw1:~# ls /tmp/stacktrace.*
/tmp/stacktrace.14502.log  /tmp/stacktrace.375.log  /tmp/stacktrace.6521.log

and caused HHVM to crash three times (/var/log/hhvm/error.log). Likely not picked up originally because HHVM OOM'd before this could be sought around.

**Comment by revi** [comment]
@arcane21 Geshi was disabled for this reason, FYI (since you requested geshi)

**Comment by Arcane21** [comment]
Alright, I understand.

**Comment by Reception123** [comment]
This extension has been requested again by a user so I think we should work on getting it fixed ASAP.

**Comment by atdt** [comment]
What is in those logs?

**Comment by Reception123** [comment]
@Southparkfan ^

**Comment by revi** [comment]
I'm not sure if we have that log by now... It was log of Sept. 30.

**Comment by Southparkfan** [comment]
We don't have the stacktraces anymore.

I've tested the REL1_26 version (which is completely rewritten) of this extension and could not reproduce the crash, so I guess this issue is no longer valid.

I hate Composer. Adding a vendor/ directory as a git submodule works 20 times better for me.

But this extension seems to work without Composer, so feel free to use it.
