### ISSUE TITLE
NativeSVGHandler (Security Review)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#380]
https://www.mediawiki.org/wiki/Extension:NativeSvgHandler for ATT.

**Comment by labster** [comment]
Other than the fact that this mixes tabs and spaces in the source code, it's clean.

Maybe will need a `global $wgNativeSvgHandlerEnableLinks;` to work correctly here:
https://github.com/p12tic/NativeSvgHandler/blob/master/NativeSvgHandler.php#L60  Might work fine without though.

Should actually improve performance (a rare change for extensions), because we'll be sending smaller vector graphics XMLs instead of generated on-the-fly PNGs.  As such, we might eventually consider this extension globally.  It will, naturally, break these images for IE < 9.  According to Piwik, we've had 135 visits from IE < 9 in the entire history (0.15%).

**Comment by labster** [comment]
Waiting on p12tic/NativeSvgHandler#7.  # 8 on that same repo would be nice, but probably won't affect our config.

**Comment by labster** [comment]
Enabled on ATT.  I'm going to enable it as a default on all wikis for reals unless someone has an objection.  I only see performance improvements and less dependencies with very minimal downside.
