### ISSUE TITLE
Vote (Security Review)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#382]
https://www.mediawiki.org/wiki/Extension:Vote for ATT.

Needs security check and maybe a 1.26 update?

**Comment by Southparkfan** [comment]
Can't we use the Poll extension for this?

**Comment by JohnFLewis** [comment]
Ask arcane or labster.

**Comment by Reception123** [comment]
@Arcane21 ^

**Comment by Arcane21** [comment]
If we have no other option, I'm sure we can do that. Labster made the same point to me in an email, and I'll bow to the logic of the situation if need be.

**Comment by labster** [comment]
@Arcane21 Uh, it's not a "no other option" thing.  It's just that one is easier than the other right now, and I don't know what the use case is that would make me prefer one extension over another.  Having us analyze and maintain 2 poll extensions when 1 would work is just a bit harder than changing a few templates.  But if there's a use case for Extension:Vote, we'd do it (and perhaps update it to MW 1.26).

**Comment by labster** [comment]
Never mind, I did a review of Extension:Poll and decided that it not very good.   https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FPoll/master/Poll_body.php#L513  That is bad code and the author should be ashamed for writing it.

The plan is to review all of the other voting extensions, and maybe put a comparison page up on mediawiki.org.  And then probably write my own, because https://xkcd.com/927/

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T193.
