### ISSUE TITLE
ClipUpload (Security)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#414]
Wanted by https://meta.miraheze.org/wiki/Request_features#Christipedia_.28Status:_2_left.29

https://www.mediawiki.org/wiki/Extension:ClipUpload

**Comment by labster** [comment]
Security review passed, conditionally.  Approved for closed/limited editing wikis, discouraged for open wikis.

I have a feeling that this extension is a crazy idea.  If it's on a wiki where editing is restricted, as in the request, I don't feel too bad about it.  But this has the potential for people to accidentally upload images.  As such, I'd have a hard time supporting its use on a wide-open wiki, if only because data can be leaked by violating the principle of least surprise.  Implementing a real version of this seems like something the VisualEditor team would need to tackle, not a little extension that only works on one browser.

Code is really well commented... if only I could read them hanzi.

**Comment by labster** [comment]
Asking the client if I can substitute Extension:MsUpload...

**Comment by labster** [comment]
... and convinced them not to do it.  Closing issue.
