### ISSUE TITLE
503 Backend fetch failed.

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#430]
503 Backend fetch failed

Our servers are having problems at the moment. Please try again in a few minutes.

Please provide the details below if you report this error to the system administrators:
Happens when trying to add permission to a user on testwiki.

**Comment by labster** [comment]
Report via http://drunkardswalkforums.yuku.com/sreply/135505/All-The-Tropes-Wiki-Project-Part-VI

Just got some "503 Backend fetch failed" errors, on both ATT and the freebie wiki. (Luckily, this was after I finished sorting the examples and adding an image to "Signature Device" - no work was lost on my end.)

**Comment by JohnFLewis** [comment]
mw2 has been really really flaky the past few days it seems.

**Comment by Reception123** [comment]
Still happening, I think it is pretty urgent to fix it.

**Comment by Southparkfan** [comment]
So, I investigated this. This is what John and I know about this:

At random (in the sense that it's not always at 8AM or 5PM) times, NGINX begins to spill out 500 or 504 errors. mw1 throws more 504 errors than 500 errors, mw2 throws more 500 errors than 504 errors.

The 500 errors are throwed by MediaWiki, because it can't contact the MariaDB server. In some cases MariaDB just ran out of memory and needs some time to restart, in other cases the error is "Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110". I'm currently looking at lowering MariaDB memory usage where possible, and I applied https://github.com/miraheze/puppet/commit/37d4a5cb26d5f660d7f01d50f227faa77dd1df59 hoping that it fixes the latter error.

The 504 error means that HHVM/PHP-FPM didn't respond in time. (Almost) all occurences of the 504 errors are because an INSERT query is a SlowTimer, or because the lock wait timeout exceeded. When one SQL query is stuck, HHVM is in a stuck state too - preventing it from serving other clients (= everyone) that do not ask for such queries being executed.

Varnish catches these errors, and depools the affected appserver(s) in an attempt to keep the site up. Unfortunately, all appservers are being depooled, with as result that Varnish throws 503 errors to everyone.

We're working on it, but the lack of collaboration with upstream (Wikimedia), RAM for db1 and extra appservers (so we can send traffic to other appservers when one or two appservers are stuck) lead into small site outages.

**Comment by Reception123** [comment]
@Southparkfan @JohnFLewis I propose putting a global notice for this issue, as it must be annoying for users.

**Comment by Reception123** [comment]
Even saving pages give me 504's!! I think this issue is URGENT!

**Comment by JohnFLewis** [comment]
As the issue is vested in MariaDB, that's not a surprise. Any active requests can generate an error (e.g. Database writes).

While saying it's urgent, the fix is a long process or alternatively hack it to work then cause bigger problems later.

**Comment by labster** [comment]
I vote for bigger problems later :P

**Comment by D66Ha** [comment]
Issue is pretty urgent!

**Comment by Reception123** [comment]
504 Gateway Time-out

nginx/1.6.2 while trying to edit/save page. Tried twice. 
@Southparkfan @JohnFLewis

**Comment by Southparkfan** [comment]
Account creation still is slow with php5-fpm, but unlike HHVM, account creation and changing settings actually works now.

I think that running purely php5-fpm is the temporary fix.

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T217.
